server:
  httpListenAddr: ":9998"
  logRequestPayloads: true


storage:
  driver: "disk" # Valid values are "disk" or "git"
  disk: # Only required if "driver" is "disk"
    directory: policy
    readOnly: true # Set to false if you want to write new policies to disk through
    watchForChanges: true # Set to true for demo purposes

